/**
 * Service Worker for مواصلات - جداول الحافلات
 * Cache Strategy: cache-first
 * Generated by PWA Converter v2.1.0
 */

'use strict';

const CACHE_NAME = 'mwasalatapp-v1';
const OFFLINE_URL = '/my-pwa-apps/mwasalatapp/offline.html';
const urlsToCache = [
  "/my-pwa-apps/mwasalatapp/favicon.ico",
  "/my-pwa-apps/mwasalatapp/",
  "/my-pwa-apps/mwasalatapp/index.html",
  "/my-pwa-apps/mwasalatapp/manifest.json",
  "/my-pwa-apps/mwasalatapp/offline.html",
  "/my-pwa-apps/mwasalatapp/icons/icon-72x72.png",
  "/my-pwa-apps/mwasalatapp/icons/icon-192x192.png",
  "/my-pwa-apps/mwasalatapp/icons/icon-384x384.png",
  "/my-pwa-apps/mwasalatapp/icons/icon-512x512.png",
  "/my-pwa-apps/mwasalatapp/routes.json",
  "/my-pwa-apps/mwasalatapp/data/azaiba-bousher.json",
  "/my-pwa-apps/mwasalatapp/data/rawi-mabaila.json",
  "/my-pwa-apps/mwasalatapp/data/rawi-wadiadi.json",
  "/my-pwa-apps/mwasalatapp/data/rawi-wadikabir-msjdjalala.json",
  "/my-pwa-apps/mwasalatapp/data/burjsahwa-khwair.json",
  "/my-pwa-apps/mwasalatapp/data/mabaila-matar-rawi.json",
  "/my-pwa-apps/mwasalatapp/data/muntazahseeb-sahwa.json"
];

self.addEventListener('install', event => {
    console.log('[Service Worker] Installing for مواصلات - جداول الحافلات...');
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then(cache => {
                console.log('[Service Worker] Caching app shell and all files for مواصلات - جداول الحافلات');
                return cache.addAll(urlsToCache);
            })
            .then(() => {
                console.log('[Service Worker] All files cached successfully for مواصلات - جداول الحافلات');
                return self.skipWaiting();
            })
            .then(() => {
                // Request persistent storage to prevent cache eviction
                if (navigator.storage && navigator.storage.persist) {
                    navigator.storage.persist().then(granted => {
                        console.log('[Service Worker] Persistent storage granted:', granted);
                    });
                }
            })
            .catch(error => {
                console.error('[Service Worker] Caching failed for مواصلات - جداول الحافلات:', error);
            })
    );
});

self.addEventListener('activate', event => {
    console.log('[Service Worker] Activating for مواصلات - جداول الحافلات...');
    // Extract app prefix from cache name (e.g. 'logo' from 'logo-v3')
    const cachePrefix = CACHE_NAME.replace(/-vd+$/, '');
    event.waitUntil(
        caches.keys().then(cacheNames => {
            return Promise.all(
                cacheNames
                    // Only delete OLD caches belonging to THIS app — not other apps' caches
                    .filter(name => name.startsWith(cachePrefix + '-') && name !== CACHE_NAME)
                    .map(name => {
                        console.log('[Service Worker] Deleting old cache:', name);
                        return caches.delete(name);
                    })
            );
        }).then(() => self.clients.claim())
    );
});

// Fetch event - Optimized Cache-First Strategy
self.addEventListener('fetch', event => {
    if (event.request.method !== 'GET') return;

    // Handle Favicon
    if (event.request.url.includes('favicon.ico')) {
        event.respondWith(
            caches.match(event.request).then(response => {
                return response || fetch(event.request).catch(() => new Response(null, { status: 204 }));
            })
        );
        return;
    }

    // Main Strategy: Cache-First
    event.respondWith(
        caches.match(event.request).then(cachedResponse => {
            // If found in cache, return immediately
            if (cachedResponse) return cachedResponse;

            // Otherwise, get from network and add to cache
            return fetch(event.request).then(response => {
                if (response && response.status === 200) {
                    const responseToCache = response.clone();
                    caches.open(CACHE_NAME).then(cache => {
                        cache.put(event.request, responseToCache);
                    });
                }
                return response;
            }).catch(() => {
                // If offline and navigating, show offline page
                if (isNavigationRequest(event.request)) {
                    return caches.match(OFFLINE_URL);
                }
            });
        })
    );
});

function isNavigationRequest(request) {
    return request.mode === 'navigate' ||
           (request.method === 'GET' && request.headers.get('accept').includes('text/html'));
}

console.log('[Service Worker] Loaded successfully for مواصلات - جداول الحافلات');
console.log('[Service Worker] Scope: /my-pwa-apps/mwasalatapp/');
