
// ============================================================================
// PWA Helper Functions (Auto-generated by PWA Converter v2.0.1)
// App: Quote Finder
// Folder: quotes
// Files: 10
// ============================================================================

/**
 * Check if app is running as PWA
 */
function isPWA() {
    return window.matchMedia('(display-mode: standalone)').matches ||
           window.navigator.standalone === true;
}

/**
 * Request persistent storage
 */
async function requestPersistentStorage() {
    if (navigator.storage && navigator.storage.persist) {
        const isPersisted = await navigator.storage.persist();
        console.log(`Persistent storage granted: ${isPersisted}`);
        return isPersisted;
    }
    return false;
}

/**
 * Check storage quota
 */
async function checkStorageQuota() {
    if (navigator.storage && navigator.storage.estimate) {
        const estimate = await navigator.storage.estimate();
        const percentUsed = (estimate.usage / estimate.quota * 100).toFixed(2);
        console.log(`Storage used: ${percentUsed}% (${estimate.usage} / ${estimate.quota} bytes)`);
        return estimate;
    }
    return null;
}

/**
 * Update online status
 */
function updateOnlineStatus() {
    const isOnline = navigator.onLine;
    const statusClass = isOnline ? 'online' : 'offline';
    document.body.classList.remove('online', 'offline');
    document.body.classList.add(statusClass);
    console.log(`App is ${statusClass}`);
    
    // Dispatch custom event
    window.dispatchEvent(new CustomEvent('connectionchange', { 
        detail: { online: isOnline } 
    }));
}

// Listen for online/offline events
window.addEventListener('online', updateOnlineStatus);
window.addEventListener('offline', updateOnlineStatus);

/**
 * Share content using Web Share API
 */
async function shareContent(title, text, url) {
    if (navigator.share) {
        try {
            await navigator.share({ title, text, url });
            console.log('Content shared successfully');
            return true;
        } catch (error) {
            console.error('Error sharing:', error);
            return false;
        }
    } else {
        console.log('Web Share API not supported');
        return false;
    }
}

/**
 * Request notification permission
 */
async function requestNotificationPermission() {
    if (!('Notification' in window)) {
        console.log('Notifications not supported');
        return false;
    }

    const permission = await Notification.requestPermission();
    console.log(`Notification permission: ${permission}`);
    return permission === 'granted';
}

/**
 * Show local notification
 */
function showNotification(title, options = {}) {
    if ('Notification' in window && Notification.permission === 'granted') {
        const notification = new Notification(title, {
            icon: '/quotes/icons/icon-192x192.png',
            badge: '/quotes/icons/icon-72x72.png',
            ...options
        });
        return notification;
    }
    return null;
}

/**
 * Register background sync
 */
async function registerBackgroundSync(tag) {
    if ('serviceWorker' in navigator && 'sync' in ServiceWorkerRegistration.prototype) {
        try {
            const registration = await navigator.serviceWorker.ready;
            await registration.sync.register(tag);
            console.log(`Background sync registered: ${tag}`);
            return true;
        } catch (error) {
            console.error('Background sync registration failed:', error);
            return false;
        }
    }
    return false;
}

// Initialize PWA features on load
document.addEventListener('DOMContentLoaded', () => {
    updateOnlineStatus();
    requestPersistentStorage();
    checkStorageQuota();
    
    console.log('🚀 PWA features initialized for Quote Finder');
    console.log('📱 Running as PWA:', isPWA());
    console.log('📂 App folder: quotes');
    console.log('📦 Total files: 10');
});

// ============================================================================
// Original Application Code
// ============================================================================

document.addEventListener('DOMContentLoaded', () => {
    // ============================================
    // COPY TO CLIPBOARD - Uses browser default notification
    // ============================================
    let copyInProgress = false;

    const performCopy = async (text, button) => {
        if (copyInProgress) return;
        copyInProgress = true;

        try {
            await navigator.clipboard.writeText(text);
            button.classList.add('copied');
            setTimeout(() => {
                button.classList.remove('copied');
            }, 1500);
        } catch (err) {
            console.error('Copy failed:', err);
        }

        setTimeout(() => {
            copyInProgress = false;
        }, 500);
    };

    // ============================================
    // TRANSLATION API - MyMemory (Free)
    // ============================================
    const translateText = async (text, fromLang, toLang) => {
        try {
            const url = `https://api.mymemory.translated.net/get?q=${encodeURIComponent(text)}&langpair=${fromLang}|${toLang}`;
            const response = await fetch(url);
            const data = await response.json();
            
            if (data.responseStatus === 200 && data.responseData) {
                return {
                    success: true,
                    translation: data.responseData.translatedText,
                    match: data.responseData.match
                };
            } else {
                return {
                    success: false,
                    error: data.responseDetails || 'Translation failed'
                };
            }
        } catch (err) {
            console.error('Translation error:', err);
            return {
                success: false,
                error: 'Network error. Please try again.'
            };
        }
    };

    // ============================================
    // SCROLL TO FIRST QUOTE
    // ============================================
    const scrollToFirstQuote = (container) => {
        setTimeout(() => {
            const firstQuote = container.querySelector('.quote-card');
            if (firstQuote) {
                const header = document.querySelector('.header');
                const headerHeight = header ? header.offsetHeight : 0;
                const rect = firstQuote.getBoundingClientRect();
                
                window.scrollTo({
                    top: window.scrollY + rect.top - headerHeight - 20,
                    behavior: 'smooth'
                });

                firstQuote.style.transition = 'box-shadow 0.3s, transform 0.3s';
                firstQuote.style.boxShadow = '0 0 0 3px var(--primary)';
                firstQuote.style.transform = 'scale(1.01)';
                
                setTimeout(() => {
                    firstQuote.style.boxShadow = '';
                    firstQuote.style.transform = '';
                }, 1500);
            }
        }, 150);
    };

    // ============================================
    // TAB SWITCHING
    // ============================================
    const tabBtns = document.querySelectorAll('.tab-btn');
    const tabContents = document.querySelectorAll('.tab-content');

    tabBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            const targetTab = btn.dataset.tab;
            tabBtns.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            tabContents.forEach(content => {
                content.classList.toggle('active', content.id === `${targetTab}-tab`);
            });
        });
    });

    // ============================================
    // ENGLISH QUOTES
    // ============================================
    const authorsListEn = document.getElementById('authors-list');
    const quotesContainerEn = document.getElementById('quotes-container-en');
    const searchBarEn = document.getElementById('search-bar-en');
    const randomBtnEn = document.getElementById('random-btn-en');

    let currentQuotesEn = [];
    let selectedAuthorEl = null;

    const sanitizeFilename = (name) => {
        if (!name) return '_empty_';
        return name.replace(/[^\w\s-]/g, '').trim().replace(/[-\s]+/g, '_').slice(0, 100);
    };

    const getInitials = (name) => {
        if (!name) return '?';
        const words = name.trim().split(/\s+/);
        return words.length === 1 
            ? words[0].charAt(0).toUpperCase() 
            : (words[0].charAt(0) + words[words.length - 1].charAt(0)).toUpperCase();
    };

    const showLoadingEn = () => {
        quotesContainerEn.innerHTML = `
            <div class="loading">
                <div class="spinner"></div>
                <p>Loading quotes...</p>
            </div>
        `;
    };

    const showEmptyEn = (title, message) => {
        quotesContainerEn.innerHTML = `
            <div class="empty-state">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                    <circle cx="12" cy="12" r="10"/>
                    <path d="M8 15h8M9 9h.01M15 9h.01"/>
                </svg>
                <h3>${title}</h3>
                <p>${message}</p>
            </div>
        `;
    };

    const displayQuotesEn = (quotes, shouldScroll = false) => {
        quotesContainerEn.innerHTML = '';

        if (!quotes.length) {
            showEmptyEn('No quotes found', 'Try a different search term.');
            return;
        }

        quotes.forEach((quote, i) => {
            const card = document.createElement('div');
            card.className = 'quote-card';
            card.style.animationDelay = `${i * 0.05}s`;

            const text = `"${quote.quote}" — ${quote.author || 'Unknown'}`;

            card.innerHTML = `
                <p class="quote-text">${quote.quote}</p>
                <div class="translation-container" style="display: none;">
                    <div class="translation-divider">
                        <span>الترجمة العربية</span>
                    </div>
                    <p class="quote-text translated-text arabic-text" dir="rtl"></p>
                </div>
                <div class="quote-meta">
                    <span class="quote-author">— ${quote.author || 'Unknown'}</span>
                    <div class="quote-actions">
                        <button class="quote-action-btn translate-btn" type="button" title="Translate to Arabic">
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <path d="M5 8l6 6M4 14l6-6 2-3M2 5h12M7 2h1M22 22l-5-10-5 10M14 18h6"/>
                            </svg>
                        </button>
                        <button class="quote-action-btn copy-btn" type="button" title="Copy">
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <rect width="14" height="14" x="8" y="8" rx="2"/>
                                <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/>
                            </svg>
                        </button>
                        <button class="quote-action-btn share-btn" type="button" title="Share">
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <circle cx="18" cy="5" r="3"/>
                                <circle cx="6" cy="12" r="3"/>
                                <circle cx="18" cy="19" r="3"/>
                                <line x1="8.59" x2="15.42" y1="13.51" y2="17.49"/>
                                <line x1="15.41" x2="8.59" y1="6.51" y2="10.49"/>
                            </svg>
                        </button>
                    </div>
                </div>
            `;

            const translationContainer = card.querySelector('.translation-container');
            const translatedText = card.querySelector('.translated-text');
            const translateBtn = card.querySelector('.translate-btn');
            let isTranslated = false;
            let cachedTranslation = null;

            translateBtn.onclick = async function(e) {
                e.stopPropagation();
                
                // Toggle translation visibility if already translated
                if (isTranslated) {
                    translationContainer.style.display = 
                        translationContainer.style.display === 'none' ? 'block' : 'none';
                    this.classList.toggle('active');
                    return;
                }

                // Show loading state
                this.classList.add('loading');
                this.disabled = true;
                translationContainer.style.display = 'block';
                translatedText.innerHTML = '<span class="translation-loading">جاري الترجمة...</span>';

                // Perform translation
                const result = await translateText(quote.quote, 'en', 'ar');

                this.classList.remove('loading');
                this.disabled = false;

                if (result.success) {
                    cachedTranslation = result.translation;
                    translatedText.textContent = result.translation;
                    isTranslated = true;
                    this.classList.add('active');
                } else {
                    translatedText.innerHTML = `<span class="translation-error">فشلت الترجمة: ${result.error}</span>`;
                }
            };

            card.querySelector('.copy-btn').onclick = function(e) {
                e.stopPropagation();
                // Copy both original and translation if available
                const copyText = cachedTranslation 
                    ? `${text}\n\n${cachedTranslation}`
                    : text;
                performCopy(copyText, this);
            };

            card.querySelector('.share-btn').onclick = async function(e) {
                e.stopPropagation();
                const shareText = cachedTranslation 
                    ? `${text}\n\n${cachedTranslation}`
                    : text;
                if (navigator.share) {
                    try {
                        await navigator.share({ title: 'Quote', text: shareText });
                    } catch (err) {
                        if (err.name !== 'AbortError') performCopy(shareText, this);
                    }
                } else {
                    performCopy(shareText, this);
                }
            };

            quotesContainerEn.appendChild(card);
        });

        if (shouldScroll) scrollToFirstQuote(quotesContainerEn);
    };

    // Load authors
    fetch('top50authors.json')
        .then(r => r.ok ? r.json() : Promise.reject('Failed'))
        .then(authors => {
            authorsListEn.innerHTML = '';
            authors.forEach(author => {
                const li = document.createElement('li');
                li.innerHTML = `
                    <span class="author-avatar">${getInitials(author.name)}</span>
                    <span>${author.name || 'Unknown'}</span>
                `;
                li.onclick = () => {
                    if (selectedAuthorEl) selectedAuthorEl.classList.remove('active');
                    li.classList.add('active');
                    selectedAuthorEl = li;
                    fetchQuotesByAuthor(author.name);
                };
                authorsListEn.appendChild(li);
            });
        })
        .catch(() => {
            authorsListEn.innerHTML = '<li>Failed to load authors.</li>';
        });

    const fetchQuotesByAuthor = (name) => {
        showLoadingEn();
        fetch(`top_authors_quotes/${sanitizeFilename(name)}.json`)
            .then(r => r.ok ? r.json() : Promise.reject(`Could not load quotes for ${name}`))
            .then(quotes => {
                currentQuotesEn = quotes;
                displayQuotesEn(quotes, true);
            })
            .catch(err => showEmptyEn('Failed to load', err));
    };

    const fetchRandomEn = async () => {
        showLoadingEn();
        if (selectedAuthorEl) {
            selectedAuthorEl.classList.remove('active');
            selectedAuthorEl = null;
        }
        try {
            const manifest = await fetch('random_quotes_splits/manifest.json').then(r => r.json());
            const idx = Math.floor(Math.random() * manifest.total_splits) + 1;
            const quotes = await fetch(`random_quotes_splits/quotes_${idx}.json`).then(r => r.json());
            const quote = quotes[Math.floor(Math.random() * quotes.length)];
            currentQuotesEn = [quote];
            displayQuotesEn([quote], true);
        } catch (err) {
            showEmptyEn('Failed to load', 'Could not fetch random quote.');
        }
    };

    searchBarEn.oninput = (e) => {
        const term = e.target.value.toLowerCase();
        if (!currentQuotesEn.length) return;
        const filtered = currentQuotesEn.filter(q =>
            q.quote.toLowerCase().includes(term) ||
            (q.author && q.author.toLowerCase().includes(term))
        );
        displayQuotesEn(filtered, false);
    };

    randomBtnEn.onclick = fetchRandomEn;

    // ============================================
    // ARABIC QUOTES
    // ============================================
    const tagsList = document.getElementById('tags-list');
    const quotesContainerAr = document.getElementById('quotes-container-ar');
    const searchBarAr = document.getElementById('search-bar-ar');
    const randomBtnAr = document.getElementById('random-btn-ar');
    const allQuotesBtnAr = document.getElementById('all-quotes-btn-ar');

    let allArabicQuotes = [];
    let currentQuotesAr = [];
    let selectedTagEl = null;

    const showLoadingAr = () => {
        quotesContainerAr.innerHTML = `
            <div class="loading">
                <div class="spinner"></div>
                <p class="arabic-text">جاري التحميل...</p>
            </div>
        `;
    };

    const showEmptyAr = (title, message) => {
        quotesContainerAr.innerHTML = `
            <div class="empty-state">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                    <circle cx="12" cy="12" r="10"/>
                    <path d="M8 15h8M9 9h.01M15 9h.01"/>
                </svg>
                <h3>${title}</h3>
                <p>${message}</p>
            </div>
        `;
    };

    const displayQuotesAr = (quotes, showHeader = false, headerTitle = '', shouldScroll = false) => {
        quotesContainerAr.innerHTML = '';

        if (!quotes.length) {
            showEmptyAr('لا توجد اقتباسات', 'جرب البحث بكلمات مختلفة.');
            return;
        }

        if (showHeader) {
            const header = document.createElement('div');
            header.className = 'results-header';
            header.innerHTML = `
                <span class="results-title arabic-text">${headerTitle}</span>
                <span class="results-count arabic-text">${quotes.length} اقتباس</span>
            `;
            quotesContainerAr.appendChild(header);
        }

        quotes.forEach((quote, i) => {
            const card = document.createElement('div');
            card.className = 'quote-card';
            card.style.animationDelay = `${i * 0.05}s`;

            const tagsHtml = quote.tags?.length
                ? `<div class="quote-tags">${quote.tags.map(t => `<span class="quote-tag">${t}</span>`).join('')}</div>`
                : '';

            card.innerHTML = `
                <p class="quote-text arabic-text">${quote.quote}</p>
                <div class="translation-container" style="display: none;">
                    <div class="translation-divider">
                        <span>English Translation</span>
                    </div>
                    <p class="quote-text translated-text"></p>
                </div>
                <div class="quote-meta">
                    ${tagsHtml}
                    <div class="quote-actions">
                        <button class="quote-action-btn translate-btn" type="button" title="ترجمة للإنجليزية">
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <path d="M5 8l6 6M4 14l6-6 2-3M2 5h12M7 2h1M22 22l-5-10-5 10M14 18h6"/>
                            </svg>
                        </button>
                        <button class="quote-action-btn copy-btn" type="button" title="نسخ">
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <rect width="14" height="14" x="8" y="8" rx="2"/>
                                <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/>
                            </svg>
                        </button>
                        <button class="quote-action-btn share-btn" type="button" title="مشاركة">
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <circle cx="18" cy="5" r="3"/>
                                <circle cx="6" cy="12" r="3"/>
                                <circle cx="18" cy="19" r="3"/>
                                <line x1="8.59" x2="15.42" y1="13.51" y2="17.49"/>
                                <line x1="15.41" x2="8.59" y1="6.51" y2="10.49"/>
                            </svg>
                        </button>
                    </div>
                </div>
            `;

            const translationContainer = card.querySelector('.translation-container');
            const translatedText = card.querySelector('.translated-text');
            const translateBtn = card.querySelector('.translate-btn');
            let isTranslated = false;
            let cachedTranslation = null;

            translateBtn.onclick = async function(e) {
                e.stopPropagation();
                
                // Toggle translation visibility if already translated
                if (isTranslated) {
                    translationContainer.style.display = 
                        translationContainer.style.display === 'none' ? 'block' : 'none';
                    this.classList.toggle('active');
                    return;
                }

                // Show loading state
                this.classList.add('loading');
                this.disabled = true;
                translationContainer.style.display = 'block';
                translatedText.innerHTML = '<span class="translation-loading">Translating...</span>';

                // Perform translation (Arabic to English)
                const result = await translateText(quote.quote, 'ar', 'en');

                this.classList.remove('loading');
                this.disabled = false;

                if (result.success) {
                    cachedTranslation = result.translation;
                    translatedText.textContent = result.translation;
                    isTranslated = true;
                    this.classList.add('active');
                } else {
                    translatedText.innerHTML = `<span class="translation-error">Translation failed: ${result.error}</span>`;
                }
            };

            card.querySelector('.copy-btn').onclick = function(e) {
                e.stopPropagation();
                const copyText = cachedTranslation 
                    ? `${quote.quote}\n\n${cachedTranslation}`
                    : quote.quote;
                performCopy(copyText, this);
            };

            card.querySelector('.share-btn').onclick = async function(e) {
                e.stopPropagation();
                const shareText = cachedTranslation 
                    ? `${quote.quote}\n\n${cachedTranslation}`
                    : quote.quote;
                if (navigator.share) {
                    try {
                        await navigator.share({ title: 'اقتباس', text: shareText });
                    } catch (err) {
                        if (err.name !== 'AbortError') performCopy(shareText, this);
                    }
                } else {
                    performCopy(shareText, this);
                }
            };

            quotesContainerAr.appendChild(card);
        });

        if (shouldScroll) scrollToFirstQuote(quotesContainerAr);
    };

    const extractTags = (quotes) => {
        const counts = {};
        quotes.forEach(q => {
            q.tags?.forEach(tag => {
                const clean = tag.replace(/[،,]$/, '').trim();
                if (clean) counts[clean] = (counts[clean] || 0) + 1;
            });
        });
        return Object.entries(counts)
            .map(([tag, count]) => ({ tag, count }))
            .sort((a, b) => b.count - a.count);
    };

    const renderTags = (tags) => {
        tagsList.innerHTML = '';
        tags.forEach(({ tag, count }) => {
            const li = document.createElement('li');
            li.innerHTML = `
                <span class="tag-icon">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <path d="M12 2H2v10l9.29 9.29c.94.94 2.48.94 3.42 0l6.58-6.58c.94-.94.94-2.48 0-3.42L12 2Z"/>
                        <path d="M7 7h.01"/>
                    </svg>
                </span>
                <span class="arabic-text">${tag}</span>
                <span class="tag-count">${count}</span>
            `;
            li.onclick = () => {
                if (selectedTagEl) selectedTagEl.classList.remove('active');
                li.classList.add('active');
                selectedTagEl = li;
                filterByTag(tag);
            };
            tagsList.appendChild(li);
        });
    };

    const filterByTag = (tag) => {
        const filtered = allArabicQuotes.filter(q =>
            q.tags?.some(t => t.replace(/[،,]$/, '').trim() === tag)
        );
        currentQuotesAr = filtered;
        displayQuotesAr(filtered, true, tag, true);
    };

    const loadArabicQuotes = () => {
        showLoadingAr();
        tagsList.innerHTML = '<li class="arabic-text">جاري التحميل...</li>';

        fetch('arabic-quotes.json')
            .then(r => r.ok ? r.json() : Promise.reject('Failed'))
            .then(quotes => {
                allArabicQuotes = quotes;
                renderTags(extractTags(quotes));
                showEmptyAr('اختر تصنيفاً', 'اختر تصنيفاً من القائمة أو احصل على اقتباس عشوائي.');
            })
            .catch(() => {
                tagsList.innerHTML = '<li class="arabic-text">فشل تحميل التصنيفات</li>';
                showEmptyAr('فشل التحميل', 'يرجى تحديث الصفحة.');
            });
    };

    randomBtnAr.onclick = () => {
        if (!allArabicQuotes.length) return;
        if (selectedTagEl) {
            selectedTagEl.classList.remove('active');
            selectedTagEl = null;
        }
        const quote = allArabicQuotes[Math.floor(Math.random() * allArabicQuotes.length)];
        currentQuotesAr = [quote];
        displayQuotesAr([quote], true, 'اقتباس عشوائي', true);
    };

    allQuotesBtnAr.onclick = () => {
        if (!allArabicQuotes.length) return;
        if (selectedTagEl) {
            selectedTagEl.classList.remove('active');
            selectedTagEl = null;
        }
        currentQuotesAr = [...allArabicQuotes];
        displayQuotesAr(allArabicQuotes, true, 'كل الاقتباسات', true);
    };

    searchBarAr.oninput = (e) => {
        const term = e.target.value.trim();
        if (!term) {
            if (currentQuotesAr.length) displayQuotesAr(currentQuotesAr);
            return;
        }
        if (selectedTagEl) {
            selectedTagEl.classList.remove('active');
            selectedTagEl = null;
        }
        const filtered = allArabicQuotes.filter(q =>
            q.quote.includes(term) || q.tags?.some(t => t.includes(term))
        );
        displayQuotesAr(filtered, true, `نتائج البحث: "${term}"`, true);
    };

    loadArabicQuotes();
});
