/**
 * Service Worker for Quote Finder
 * Generated by PWA Converter v2.0.1
 * Cache Strategy: stale-while-revalidate
 * Folder: quotes
 * Total Files Cached: 14
 */

const CACHE_NAME = 'quotes-v1';
const OFFLINE_URL = '/quotes/offline.html';

const urlsToCache = [
  "/quotes/",
  "/quotes/index.html",
  "/quotes/manifest.json",
  "/quotes/arabic-quotes.json",
  "/quotes/app.js",
  "/quotes/top50authors.json",
  "/quotes/top50categories.json",
  "/quotes/index.html",
  "/quotes/random_quotes_splits/quotes_1.json",
  "/quotes/random_quotes_splits/quotes_11.json",
  "/quotes/random_quotes_splits/manifest.json",
  "/quotes/top_authors_quotes/William_Shakespeare.json",
  "/quotes/top_authors_quotes/miscellaneous_1.json",
  "/quotes/offline.html"
];

// Install event - cache ALL resources
self.addEventListener('install', event => {
    console.log('[Service Worker] Installing for Quote Finder...');
    console.log('[Service Worker] Caching 14 files...');
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then(cache => {
                console.log('[Service Worker] Caching app shell and all files');
                return cache.addAll(urlsToCache);
            })
            .then(() => {
                console.log('[Service Worker] All files cached successfully');
                return self.skipWaiting();
            })
            .catch(error => {
                console.error('[Service Worker] Cache failed:', error);
            })
    );
});

// Activate event - clean up old caches
self.addEventListener('activate', event => {
    console.log('[Service Worker] Activating...');
    event.waitUntil(
        caches.keys().then(cacheNames => {
            return Promise.all(
                cacheNames
                    .filter(name => name !== CACHE_NAME)
                    .map(name => {
                        console.log('[Service Worker] Deleting old cache:', name);
                        return caches.delete(name);
                    })
            );
        }).then(() => self.clients.claim())
    );
});

// Fetch event - serve from cache or network
self.addEventListener('fetch', event => {
        // Stale While Revalidate Strategy - Balanced approach
    if (event.request.method !== 'GET') {
        return;
    }

    event.respondWith(
        caches.match(event.request).then(cachedResponse => {
            const fetchPromise = fetch(event.request).then(response => {
                if (response.status === 200) {
                    const responseToCache = response.clone();
                    caches.open(CACHE_NAME).then(cache => {
                        cache.put(event.request, responseToCache);
                    });
                }
                return response;
            }).catch(error => {
                
                if (isNavigationRequest(event.request)) {
                    return caches.match(OFFLINE_URL);
                }
                throw error;
            });

            return cachedResponse || fetchPromise;
        })
    );
});



// Background sync (if supported)
self.addEventListener('sync', event => {
    if (event.tag === 'sync-data') {
        event.waitUntil(syncData());
    }
});

async function syncData() {
    console.log('[Service Worker] Background sync triggered');
    // Implement your sync logic here
}

// Helper function to check if request is navigational
function isNavigationRequest(request) {
    return request.mode === 'navigate' || 
           (request.method === 'GET' && request.headers.get('accept').includes('text/html'));
}

console.log('[Service Worker] Loaded successfully for Quote Finder');
console.log('[Service Worker] Scope: /quotes/');
console.log('[Service Worker] Caching 14 files including all your assets');