/**
 * Service Worker for Logo Generator Pro
 * Generated by PWA Converter v2.0.1
 * Cache Strategy: stale-while-revalidate
 * Folder: logo
 * Total Files Cached: 5
 */

const CACHE_NAME = 'logo-v5';
const OFFLINE_URL = '/logo/offline.html';

const urlsToCache = [
  "/logo/favicon.ico",
  "/logo/",
  "/logo/index.html",
  "/logo/manifest.json",
  "/logo/offline.html",
  "/logo/icons/icon-72x72.png",
  "/logo/icons/icon-96x96.png",
  "/logo/icons/icon-128x128.png",
  "/logo/icons/icon-144x144.png",
  "/logo/icons/icon-152x152.png",
  "/logo/icons/icon-192x192.png",
  "/logo/icons/icon-384x384.png",
  "/logo/icons/icon-512x512.png"
];

// Install event - cache ALL resources
self.addEventListener('install', event => {
    console.log('[Service Worker] Installing for Logo Generator Pro...');
    console.log('[Service Worker] Caching 5 files...');
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then(cache => {
                console.log('[Service Worker] Caching app shell and all files');
                return cache.addAll(urlsToCache);
            })
            .then(() => {
                console.log('[Service Worker] All files cached successfully');
                return self.skipWaiting();
            }).then(() => {
                // Request persistent storage to prevent cache eviction
                if (navigator.storage && navigator.storage.persist) {
                    navigator.storage.persist().then(granted => {
                        console.log('[Service Worker] Persistent storage granted:', granted);
                    });
                }
            })
            .catch(error => {
                console.error('[Service Worker] Cache failed:', error);
            })
    );
});

// Activate event - clean up old caches
self.addEventListener('activate', event => {
    console.log('[Service Worker] Activating...');
    event.waitUntil(
        caches.keys().then(cacheNames => {
            return Promise.all(
                cacheNames
                    .filter(name => {
                        const cachePrefix = CACHE_NAME.replace(/-v\d+$/, "");
                        return name.startsWith(cachePrefix + "-") && name !== CACHE_NAME;
                    })
                    .map(name => {
                        console.log('[Service Worker] Deleting old cache:', name);
                        return caches.delete(name);
                    })
            );
        }).then(() => self.clients.claim())
    );
});

// Fetch event - Optimized Cache-First Strategy
self.addEventListener('fetch', event => {
    if (event.request.method !== 'GET') return;

    // Handle Favicon
    if (event.request.url.includes('favicon.ico')) {
        event.respondWith(
            caches.match(event.request).then(response => {
                return response || fetch(event.request).catch(() => new Response(null, { status: 204 }));
            })
        );
        return;
    }

    // Main Strategy: Cache-First
    event.respondWith(
        caches.match(event.request).then(cachedResponse => {
            // If found in cache, return immediately
            if (cachedResponse) return cachedResponse;

            // Otherwise, get from network and add to cache
            return fetch(event.request).then(response => {
                if (response && response.status === 200) {
                    const responseToCache = response.clone();
                    caches.open(CACHE_NAME).then(cache => {
                        cache.put(event.request, responseToCache);
                    });
                }
                return response;
            }).catch(() => {
                // If offline and navigating, show offline page
                if (isNavigationRequest(event.request)) {
                    return caches.match(OFFLINE_URL);
                }
            });
        })
    );
});



// Background sync (if supported)
self.addEventListener('sync', event => {
    if (event.tag === 'sync-data') {
        event.waitUntil(syncData());
    }
});

async function syncData() {
    console.log('[Service Worker] Background sync triggered');
    // Implement your sync logic here
}

// Helper function to check if request is navigational
function isNavigationRequest(request) {
    return request.mode === 'navigate' || 
           (request.method === 'GET' && request.headers.get('accept').includes('text/html'));
}

console.log('[Service Worker] Loaded successfully for Logo Generator Pro');
console.log('[Service Worker] Scope: /logo/');
console.log('[Service Worker] Caching 5 files including all your assets');
