
// ============================================================================
// PWA Helper Functions (Auto-generated by PWA Converter v2.0.1)
// App: Website Prompt Builder - HTML/CSS/JS
// Folder: promaker
// Files: 5
// ============================================================================

/**
 * Check if app is running as PWA
 */
function isPWA() {
    return window.matchMedia('(display-mode: standalone)').matches ||
           window.navigator.standalone === true;
}

/**
 * Request persistent storage
 */
async function requestPersistentStorage() {
    if (navigator.storage && navigator.storage.persist) {
        const isPersisted = await navigator.storage.persist();
        console.log(`Persistent storage granted: ${isPersisted}`);
        return isPersisted;
    }
    return false;
}

/**
 * Check storage quota
 */
async function checkStorageQuota() {
    if (navigator.storage && navigator.storage.estimate) {
        const estimate = await navigator.storage.estimate();
        const percentUsed = (estimate.usage / estimate.quota * 100).toFixed(2);
        console.log(`Storage used: ${percentUsed}% (${estimate.usage} / ${estimate.quota} bytes)`);
        return estimate;
    }
    return null;
}

/**
 * Update online status
 */
function updateOnlineStatus() {
    const isOnline = navigator.onLine;
    const statusClass = isOnline ? 'online' : 'offline';
    document.body.classList.remove('online', 'offline');
    document.body.classList.add(statusClass);
    console.log(`App is ${statusClass}`);
    
    // Dispatch custom event
    window.dispatchEvent(new CustomEvent('connectionchange', { 
        detail: { online: isOnline } 
    }));
}

// Listen for online/offline events
window.addEventListener('online', updateOnlineStatus);
window.addEventListener('offline', updateOnlineStatus);

/**
 * Share content using Web Share API
 */
async function shareContent(title, text, url) {
    if (navigator.share) {
        try {
            await navigator.share({ title, text, url });
            console.log('Content shared successfully');
            return true;
        } catch (error) {
            console.error('Error sharing:', error);
            return false;
        }
    } else {
        console.log('Web Share API not supported');
        return false;
    }
}

/**
 * Request notification permission
 */
async function requestNotificationPermission() {
    if (!('Notification' in window)) {
        console.log('Notifications not supported');
        return false;
    }

    const permission = await Notification.requestPermission();
    console.log(`Notification permission: ${permission}`);
    return permission === 'granted';
}

/**
 * Show local notification
 */
function showNotification(title, options = {}) {
    if ('Notification' in window && Notification.permission === 'granted') {
        const notification = new Notification(title, {
            icon: '/promaker/icons/icon-192x192.png',
            badge: '/promaker/icons/icon-72x72.png',
            ...options
        });
        return notification;
    }
    return null;
}

/**
 * Register background sync
 */
async function registerBackgroundSync(tag) {
    if ('serviceWorker' in navigator && 'sync' in ServiceWorkerRegistration.prototype) {
        try {
            const registration = await navigator.serviceWorker.ready;
            await registration.sync.register(tag);
            console.log(`Background sync registered: ${tag}`);
            return true;
        } catch (error) {
            console.error('Background sync registration failed:', error);
            return false;
        }
    }
    return false;
}

// Initialize PWA features on load
document.addEventListener('DOMContentLoaded', () => {
    updateOnlineStatus();
    requestPersistentStorage();
    checkStorageQuota();
    
    console.log('🚀 PWA features initialized for Website Prompt Builder - HTML/CSS/JS');
    console.log('📱 Running as PWA:', isPWA());
    console.log('📂 App folder: promaker');
    console.log('📦 Total files: 5');
});

// ============================================================================
// Original Application Code
// ============================================================================

document.addEventListener('DOMContentLoaded', () => {
    let componentCategories;
    let projectTemplates;

    let selectedComponents = {};
    let componentParameters = {};
    let activeTab = 'general';

    const templatesContainer = document.getElementById('templates-container');
    const tabsList = document.getElementById('tabs-list');
    const tabsContent = document.getElementById('tabs-content');
    const generatePromptBtn = document.getElementById('generate-prompt');
    const clearAllBtn = document.getElementById('clear-all');
    const promptTextarea = document.getElementById('prompt-textarea');
    const copyPromptBtn = document.getElementById('copy-prompt');
    const downloadPromptBtn = document.getElementById('download-prompt');
    const selectedComponentsList = document.getElementById('selected-components-list');
    const selectedComponentsCount = document.getElementById('selected-components-count');
    const sidebarTabsList = document.getElementById('sidebar-tabs-list');
    const sidebarTabsContent = document.getElementById('sidebar-tabs-content');
    const generatedPromptContainer = document.getElementById('generated-prompt-container');
    const promptActions = document.getElementById('prompt-actions');
    const mockupComponentsContainer = document.getElementById('mockup-components-container');
    const viewModeToggles = document.getElementById('view-mode-toggles');
    const previewViewport = document.getElementById('preview-viewport');
    const previewDescription = document.getElementById('preview-description');

    const tryPromptBtn = document.getElementById('try-prompt-btn');
    const aiToolsModal = document.getElementById('ai-tools-modal');
    const closeModalBtn = document.getElementById('close-modal-btn');
    const aiToolsGrid = document.querySelector('.ai-tools-grid');

    function renderAiTools(aiTools) {
        if (!aiToolsGrid) return;
        aiToolsGrid.innerHTML = '';
        aiTools.forEach(tool => {
            const toolCard = document.createElement('div');
            toolCard.className = 'ai-tool-card';
            toolCard.innerHTML = `
                <h3>${tool.name}</h3>
                <p>${tool.description}</p>
                <a href="${tool.url}" target="_blank" class="ai-tool-link">Try ${tool.name}</a>
            `;
            aiToolsGrid.appendChild(toolCard);
        });
    }

    function renderTemplates() {
        templatesContainer.innerHTML = '';
        for (const templateName in projectTemplates) {
            const button = document.createElement('button');
            button.className = 'btn btn-outline';
            button.innerHTML = `<span class="template-title">${templateName}</span><span class="template-desc">Pre-configured components</span>`;
            button.addEventListener('click', () => applyTemplate(templateName));
            templatesContainer.appendChild(button);
        }
    }

    function renderTabs() {
        tabsList.innerHTML = '';
        Object.keys(componentCategories).forEach(key => {
            const category = componentCategories[key];
            const button = document.createElement('button');
            button.className = `tab-trigger ${key === activeTab ? 'active' : ''}`;
            button.dataset.tab = key;
            button.innerHTML = `${category.icon} <span class="hidden sm:inline">${category.title.split(' ')[0]}</span>`;
            button.addEventListener('click', () => setActiveTab(key));
            tabsList.appendChild(button);
        });
    }

    function renderTabContent() {
        tabsContent.innerHTML = '';
        Object.keys(componentCategories).forEach(key => {
            const category = componentCategories[key];
            const contentDiv = document.createElement('div');
            contentDiv.id = key;
            contentDiv.className = `tab-content ${key === activeTab ? 'active' : ''}`;

            Object.entries(category.components).forEach(([componentName, types]) => {
                const isChecked = selectedComponents[key] && selectedComponents[key][componentName];
                const selectedType = isChecked ? selectedComponents[key][componentName] : types[0];

                const itemDiv = document.createElement('div');
                itemDiv.className = 'component-item';
                itemDiv.innerHTML = `
                    <label class="component-label">
                        <input type="checkbox" data-category="${key}" data-component="${componentName}" ${isChecked ? 'checked' : ''}>
                        ${componentName}
                    </label>
                    <div class="component-options">
                        <select class="select" data-category="${key}" data-component="${componentName}">
                            ${types.map(type => `<option value="${type}" ${type === selectedType ? 'selected' : ''}>${type}</option>`).join('')}
                        </select>
                    </div>
                `;
                contentDiv.appendChild(itemDiv);
            });
            tabsContent.appendChild(contentDiv);
        });

        tabsContent.querySelectorAll('input[type="checkbox"]').forEach(checkbox => {
            checkbox.addEventListener('change', handleComponentChange);
        });
        tabsContent.querySelectorAll('select').forEach(select => {
            select.addEventListener('change', handleComponentTypeChange);
        });
    }

    function handleComponentChange(event) {
        const { category, component } = event.target.dataset;
        const isChecked = event.target.checked;
        const optionsDiv = event.target.closest('.component-item').querySelector('.component-options');

        if (!selectedComponents[category]) {
            selectedComponents[category] = {};
        }

        if (isChecked) {
            const select = optionsDiv.querySelector('select');
            selectedComponents[category][component] = select.value;
            optionsDiv.style.display = 'block';
        } else {
            delete selectedComponents[category][component];
            optionsDiv.style.display = 'none';
        }
        updateSelectedComponentsUI();
    }

    function handleComponentTypeChange(event) {
        const { category, component } = event.target.dataset;
        if (selectedComponents[category] && selectedComponents[category][component]) {
            selectedComponents[category][component] = event.target.value;
        }
        updateSelectedComponentsUI();
    }

    function setActiveTab(key) {
        activeTab = key;
        renderTabs();
        renderTabContent();
    }

    function applyTemplate(templateName) {
        const template = projectTemplates[templateName];
        if (!template) return;

        selectedComponents = {};

        if (template.general) {
            selectedComponents.general = {
                [template.general.component]: template.general.type
            };
        }
        if (template.basic) {
            selectedComponents.basic = {};
            template.basic.forEach(item => {
                selectedComponents.basic[item.component] = item.type;
            });
        }
        if (template.advanced) {
            selectedComponents.advanced = {};
            template.advanced.forEach(item => {
                selectedComponents.advanced[item.component] = item.type;
            });
        }

        document.querySelectorAll('#templates-container .btn').forEach(btn => {
            if (btn.querySelector('.template-title').textContent === templateName) {
                btn.classList.add('active');
            } else {
                btn.classList.remove('active');
            }
        });

        renderTabContent();
        updateSelectedComponentsUI();
    }

    function generatePrompt() {
        const selected = [];
        Object.entries(selectedComponents).forEach(([category, components]) => {
            Object.entries(components).forEach(([component, type]) => {
                selected.push({ component, type });
            });
        });

        if (selected.length === 0) {
            promptTextarea.value = 'Please select at least one component.';
            return;
        }

        let prompt = 'You are a full-stack web application developer. ';
        prompt += 'Create a modern, responsive single-page web application';

        const generalSelection = selectedComponents.general;
        if (generalSelection) {
            const generalType = Object.values(generalSelection)[0];
            if (generalType) {
                prompt += ` for ${generalType.toLowerCase()}`;
            }
        }

        prompt += ' that incorporates ALL of the following components into a complete, fully integrated app:\n\n';

        selected.forEach(item => {
            let componentDescription = `• ${item.component} with a ${item.type.toLowerCase()} implementation`;
            prompt += componentDescription + '\n';
        });

        prompt += '\nRequirements:\n';
        prompt += '• Use modern web technologies (HTML5, CSS3, JavaScript ES6+)\n';
        prompt += '• Implement responsive design for mobile, tablet, and desktop\n';
        prompt += '• Include meaningful test data and placeholder content\n';
        prompt += '• Provide a single, cohesive HTML file with embedded CSS and JavaScript\n';

        promptTextarea.value = prompt;
        generatedPromptContainer.style.display = 'none';
        promptTextarea.style.display = 'block';
        promptActions.style.display = 'flex';
        switchSidebarTab('prompt-tab');
    }

    function clearAll() {
        selectedComponents = {};
        componentParameters = {};
        promptTextarea.value = '';
        document.querySelectorAll('#templates-container .btn').forEach(btn => btn.classList.remove('active'));
        renderTabContent();
        updateSelectedComponentsUI();
        generatedPromptContainer.style.display = 'block';
        promptTextarea.style.display = 'none';
        promptActions.style.display = 'none';
    }

    function updateSelectedComponentsUI() {
        selectedComponentsList.innerHTML = '';
        let count = 0;

        Object.entries(selectedComponents).forEach(([category, components]) => {
            Object.entries(components).forEach(([component, type]) => {
                count++;
                const item = document.createElement('div');
                item.className = 'selected-component-item';
                item.innerHTML = `
                    <span class="badge">${category}</span>
                    <div class="selected-component-details">
                        <div class="selected-component-title">${component}</div>
                        <div class="selected-component-type">${type}</div>
                    </div>
                `;
                selectedComponentsList.appendChild(item);
            });
        });

        if (count === 0) {
            selectedComponentsList.innerHTML = `
                <div class="empty-state">
                    <div class="empty-icon">📝</div>
                    <p>No components selected yet</p>
                </div>
            `;
        }
        selectedComponentsCount.textContent = `${count} components selected`;
        renderPreview();
    }

    function setupSidebarTabs() {
        sidebarTabsList.addEventListener('click', (e) => {
            if (e.target.classList.contains('tab-trigger')) {
                const tabId = e.target.dataset.tab;
                switchSidebarTab(tabId);
            }
        });
    }

    function switchSidebarTab(tabId) {
        sidebarTabsList.querySelectorAll('.tab-trigger').forEach(btn => {
            if (btn.dataset.tab === tabId) {
                btn.classList.add('active');
            } else {
                btn.classList.remove('active');
            }
        });

        sidebarTabsContent.querySelectorAll('.tab-content').forEach(content => {
            if (content.id === tabId) {
                content.classList.add('active');
            } else {
                content.classList.remove('active');
            }
        });
    }

    function getComponentOrder(component) {
        const order = {
            'Logo': 1, 'Header': 2, 'Navigation Bar': 3, 'Hero Section': 4, 'Search Bar': 5,
            'Breadcrumbs': 6, 'Content Area': 7, 'Slider': 8, 'Feature/Product Cards': 9,
            'Blog Section': 10, 'Forms': 11, 'Sidebar': 12, 'Call to Action (CTA)': 13,
            'Social Media Links': 14, 'Footer': 15
        };
        return order[component] || 99;
    }

    function getComponentMockupHTML(comp) {
        const { component, type, category } = comp;

        let content = '';
        switch (component) {
            case 'Logo':
                content = `<div class="mockup-logo"><div class="mockup-logo-box"></div><span class="mockup-logo-text">Logo</span></div>`;
                break;
            case 'Header':
                content = `<div class="mockup-header"><div class="mockup-header-title">Header</div><div class="mockup-header-type">${type}</div></div>`;
                break;
            case 'Navigation Bar':
                content = `<div class="mockup-nav"><div class="mockup-nav-links"><span>Home</span><span>About</span><span>Services</span><span>Contact</span></div></div>`;
                break;
            case 'Hero Section':
                content = `<div class="mockup-hero"><h2 class="mockup-hero-title">Hero Section</h2><p class="mockup-hero-type">${type}</p></div>`;
                break;
            case 'Search Bar':
                content = `<div class="mockup-search"><div class="mockup-search-inner"><input class="mockup-search-input" placeholder="Search..." disabled /><button class="mockup-search-btn">Search</button></div></div>`;
                break;
            case 'Content Area':
                content = `<div class="mockup-content"><div class="mockup-content-inner"><div class="mockup-content-line" style="width: 75%;"></div><div class="mockup-content-line" style="width: 50%;"></div><div class="mockup-content-line" style="width: 90%;"></div></div></div>`;
                break;
            case 'Feature/Product Cards':
                content = `<div class="mockup-cards">${[1, 2, 3].map(() => `<div class="mockup-card-item"><div class="mockup-card-img"></div><div class="mockup-card-line"></div></div>`).join('')}</div>`;
                break;
            case 'Forms':
                content = `<div class="mockup-form"><div class="mockup-form-input"></div><div class="mockup-form-input"></div><button class="mockup-form-button">Submit</button></div>`;
                break;
            case 'Social Media Links':
                content = `<div class="mockup-social-links">${['f', 't', 'in'].map(social => `<div class="mockup-social-icon">${social}</div>`).join('')}</div>`;
                break;
            case 'Slider':
                content = `<div class="mockup-slider"><div class="mockup-slider-item"></div><div class="mockup-slider-item"></div><div class="mockup-slider-item"></div></div>`;
                break;
            case 'Sidebar':
                content = `<div class="mockup-sidebar"><div class="mockup-sidebar-item"></div><div class="mockup-sidebar-item"></div><div class="mockup-sidebar-item"></div></div>`;
                break;
            case 'Call to Action (CTA)':
                content = `<div class="mockup-cta"><button class="mockup-cta-button">Call to Action</button></div>`;
                break;
            case 'Breadcrumbs':
                content = `<div class="mockup-breadcrumbs"><span>Home</span> &gt; <span>Page</span></div>`;
                break;
            default:
                content = `<div class="mockup-default"><div class="mockup-default-title">${component}</div><div class="mockup-default-type">${type}</div></div>`;
                break;
        }
        return `<div class="mockup-component">${content}<div class="mockup-badge">${category}</div></div>`;
    }

    function renderPreview() {
        if (!mockupComponentsContainer) return;
        const components = [];
        Object.entries(selectedComponents).forEach(([category, categoryComponents]) => {
            Object.entries(categoryComponents).forEach(([component, type]) => {
                components.push({ category, component, type, id: `${category}-${component}`, order: getComponentOrder(component) });
            });
        });

        components.sort((a, b) => a.order - b.order);

        if (components.length === 0) {
            mockupComponentsContainer.innerHTML = `<div class="empty-state"><div class="empty-icon">🖼️</div><p>Select components to see a preview</p></div>`;
            if(previewDescription) previewDescription.textContent = '';
            return;
        }

        mockupComponentsContainer.innerHTML = components.map(getComponentMockupHTML).join('');
        if(previewViewport && previewDescription){
            const currentViewMode = previewViewport.classList.contains('desktop') ? 'desktop' : previewViewport.classList.contains('tablet') ? 'tablet' : 'mobile';
            previewDescription.textContent = `Preview shows ${components.length} components in ${currentViewMode} view.`;
        }
    }

    function setupPreview() {
        if (!viewModeToggles) return;
        viewModeToggles.addEventListener('click', (e) => {
            if (e.target.classList.contains('view-mode-btn')) {
                const view = e.target.dataset.view;
                
                viewModeToggles.querySelectorAll('.view-mode-btn').forEach(btn => btn.classList.remove('active'));
                e.target.classList.add('active');

                previewViewport.classList.remove('desktop', 'tablet', 'mobile');
                previewViewport.classList.add(view);
                renderPreview();
            }
        });
    }

    // Event Listeners
    generatePromptBtn.addEventListener('click', generatePrompt);
    clearAllBtn.addEventListener('click', clearAll);
    copyPromptBtn.addEventListener('click', () => navigator.clipboard.writeText(promptTextarea.value));
    if (downloadPromptBtn) {
        downloadPromptBtn.addEventListener('click', () => {
            const blob = new Blob([promptTextarea.value], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'website-prompt.txt';
            a.click();
            URL.revokeObjectURL(url);
        });
    }

    tryPromptBtn.addEventListener('click', () => {
        aiToolsModal.style.display = 'flex';
    });

    closeModalBtn.addEventListener('click', () => {
        aiToolsModal.style.display = 'none';
    });

    aiToolsModal.addEventListener('click', (event) => {
        if (event.target === aiToolsModal) {
            aiToolsModal.style.display = 'none';
        }
    });

    // Initial Render
    fetch('data.json')
        .then(response => response.json())
        .then(data => {
            componentCategories = data.componentCategories;
            projectTemplates = data.projectTemplates;

            renderTemplates();
            renderTabs();
            renderTabContent();
            updateSelectedComponentsUI();
            setupSidebarTabs();
            setupPreview();
            if (data.aiTools) {
                renderAiTools(data.aiTools);
            }
        })
        .catch(error => console.error('Error loading component data:', error));
});
