/**
 * Service Worker for القبلة – Qibla Compass
 * Cache Strategy: stale-while-revalidate
 * Generated by PWA Converter v2.0.2
 */

'use strict';

const CACHE_NAME = 'qibla-gh1';
const OFFLINE_URL = '/qibla/offline.html';
const URLS_TO_CACHE = [
  "/my-pwa-apps/qibla/",
  "/my-pwa-apps/qibla/index.html",
  "/my-pwa-apps/qibla/manifest.json",
  "/my-pwa-apps/qibla/offline.html",
  "/my-pwa-apps/qibla/locations.json"
];

self.addEventListener('install', event => {
    console.log('[Service Worker] Installing for القبلة – Qibla Compass...');
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then(cache => {
                console.log('[Service Worker] Caching app shell and all files for القبلة – Qibla Compass');
                return cache.addAll(URLS_TO_CACHE);
            })
            .then(() => {
                console.log('[Service Worker] All files cached successfully for القبلة – Qibla Compass');
                return self.skipWaiting();
            })
            .catch(error => {
                console.error('[Service Worker] Caching failed for القبلة – Qibla Compass:', error);
            })
    );
});

self.addEventListener('activate', event => {
    console.log('[Service Worker] Activating for القبلة – Qibla Compass...');
    event.waitUntil(
        caches.keys().then(cacheNames => {
            return Promise.all(
                cacheNames
                    .filter(name => name !== CACHE_NAME)
                    .map(name => {
                        console.log('[Service Worker] Deleting old cache:', name);
                        return caches.delete(name);
                    })
            );
        }).then(() => self.clients.claim())
    );
});

self.addEventListener('fetch', event => {
// Stale While Revalidate Strategy
    if (event.request.method !== 'GET') {
        return;
    }

    event.respondWith(
        caches.match(event.request).then(cachedResponse => {
            const fetchPromise = fetch(event.request).then(response => {
                // Check if we received a valid response
                if (response && response.status === 200) {
                    const responseToCache = response.clone();
                    caches.open(CACHE_NAME).then(cache => {
                        cache.put(event.request, responseToCache);
                    });
                }
                return response;
            }).catch(error => {
                // If the network request fails, and it's a navigation request,
                // serve the offline page.
                console.error('[Service Worker] Fetch failed; returning offline page if navigation.', error);
                if (isNavigationRequest(event.request)) {
                    return caches.match(OFFLINE_URL);
                }
            });

            // Return the cached response if it exists, otherwise wait for the network
            return cachedResponse || fetchPromise;
        })
    );
});

function isNavigationRequest(request) {
    return request.mode === 'navigate' || 
           (request.method === 'GET' && request.headers.get('accept').includes('text/html'));
}

console.log('[Service Worker] Loaded successfully for القبلة – Qibla Compass');