/**
 * Service Worker for مع القرآن الكريم
 * Generated by PWA Converter v2.0.1
 * Cache Strategy: stale-while-revalidate
 * Folder: discoverquran
 * Total Files Cached: 19
 */

const CACHE_NAME = 'discoverquran-v1';
const OFFLINE_URL = '/discoverquran/offline.html';

const urlsToCache = [
  "/discoverquran/",
  "/discoverquran/index.html",
  "/discoverquran/manifest.json",
  "/discoverquran/.gitignore",
  "/discoverquran/Gfe6Xxzaw.jpg",
  "/discoverquran/KpWQhgRnd1.jpg",
  "/discoverquran/README.md",
  "/discoverquran/favicon.ico",
  "/discoverquran/fgYdWjAl.jpg",
  "/discoverquran/hGfVkpbyda.jpg",
  "/discoverquran/heroimage.jpg",
  "/discoverquran/hjKEn76bwsh2.jpg",
  "/discoverquran/index.html",
  "/discoverquran/owgj23Ftaym.jpg",
  "/discoverquran/quran.json",
  "/discoverquran/search.html",
  "/discoverquran/tjd_kMdObwsh1.jpg",
  "/discoverquran/uuVHgrAnd2.jpg",
  "/discoverquran/offline.html"
];

// Install event - cache ALL resources
self.addEventListener('install', event => {
    console.log('[Service Worker] Installing for مع القرآن الكريم...');
    console.log('[Service Worker] Caching 19 files...');
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then(cache => {
                console.log('[Service Worker] Caching app shell and all files');
                return cache.addAll(urlsToCache);
            })
            .then(() => {
                console.log('[Service Worker] All files cached successfully');
                return self.skipWaiting();
            })
            .catch(error => {
                console.error('[Service Worker] Cache failed:', error);
            })
    );
});

// Activate event - clean up old caches
self.addEventListener('activate', event => {
    console.log('[Service Worker] Activating...');
    event.waitUntil(
        caches.keys().then(cacheNames => {
            return Promise.all(
                cacheNames
                    .filter(name => name !== CACHE_NAME)
                    .map(name => {
                        console.log('[Service Worker] Deleting old cache:', name);
                        return caches.delete(name);
                    })
            );
        }).then(() => self.clients.claim())
    );
});

// Fetch event - serve from cache or network
self.addEventListener('fetch', event => {
        // Stale While Revalidate Strategy - Balanced approach
    if (event.request.method !== 'GET') {
        return;
    }

    event.respondWith(
        caches.match(event.request).then(cachedResponse => {
            const fetchPromise = fetch(event.request).then(response => {
                if (response.status === 200) {
                    const responseToCache = response.clone();
                    caches.open(CACHE_NAME).then(cache => {
                        cache.put(event.request, responseToCache);
                    });
                }
                return response;
            }).catch(error => {
                
                if (isNavigationRequest(event.request)) {
                    return caches.match(OFFLINE_URL);
                }
                throw error;
            });

            return cachedResponse || fetchPromise;
        })
    );
});



// Background sync (if supported)
self.addEventListener('sync', event => {
    if (event.tag === 'sync-data') {
        event.waitUntil(syncData());
    }
});

async function syncData() {
    console.log('[Service Worker] Background sync triggered');
    // Implement your sync logic here
}

// Helper function to check if request is navigational
function isNavigationRequest(request) {
    return request.mode === 'navigate' || 
           (request.method === 'GET' && request.headers.get('accept').includes('text/html'));
}

console.log('[Service Worker] Loaded successfully for مع القرآن الكريم');
console.log('[Service Worker] Scope: /discoverquran/');
console.log('[Service Worker] Caching 19 files including all your assets');