
// ============================================================================
// PWA Helper Functions (Auto-generated by PWA Converter v2.0.1)
// App: Simple Media Browser
// Folder: openverse
// Files: 4
// ============================================================================

/**
 * Check if app is running as PWA
 */
function isPWA() {
    return window.matchMedia('(display-mode: standalone)').matches ||
           window.navigator.standalone === true;
}

/**
 * Request persistent storage
 */
async function requestPersistentStorage() {
    if (navigator.storage && navigator.storage.persist) {
        const isPersisted = await navigator.storage.persist();
        console.log(`Persistent storage granted: ${isPersisted}`);
        return isPersisted;
    }
    return false;
}

/**
 * Check storage quota
 */
async function checkStorageQuota() {
    if (navigator.storage && navigator.storage.estimate) {
        const estimate = await navigator.storage.estimate();
        const percentUsed = (estimate.usage / estimate.quota * 100).toFixed(2);
        console.log(`Storage used: ${percentUsed}% (${estimate.usage} / ${estimate.quota} bytes)`);
        return estimate;
    }
    return null;
}

/**
 * Update online status
 */
function updateOnlineStatus() {
    const isOnline = navigator.onLine;
    const statusClass = isOnline ? 'online' : 'offline';
    document.body.classList.remove('online', 'offline');
    document.body.classList.add(statusClass);
    console.log(`App is ${statusClass}`);
    
    // Dispatch custom event
    window.dispatchEvent(new CustomEvent('connectionchange', { 
        detail: { online: isOnline } 
    }));
}

// Listen for online/offline events
window.addEventListener('online', updateOnlineStatus);
window.addEventListener('offline', updateOnlineStatus);

/**
 * Share content using Web Share API
 */
async function shareContent(title, text, url) {
    if (navigator.share) {
        try {
            await navigator.share({ title, text, url });
            console.log('Content shared successfully');
            return true;
        } catch (error) {
            console.error('Error sharing:', error);
            return false;
        }
    } else {
        console.log('Web Share API not supported');
        return false;
    }
}

/**
 * Request notification permission
 */
async function requestNotificationPermission() {
    if (!('Notification' in window)) {
        console.log('Notifications not supported');
        return false;
    }

    const permission = await Notification.requestPermission();
    console.log(`Notification permission: ${permission}`);
    return permission === 'granted';
}

/**
 * Show local notification
 */
function showNotification(title, options = {}) {
    if ('Notification' in window && Notification.permission === 'granted') {
        const notification = new Notification(title, {
            icon: '/openverse/icons/icon-192x192.png',
            badge: '/openverse/icons/icon-72x72.png',
            ...options
        });
        return notification;
    }
    return null;
}

/**
 * Register background sync
 */
async function registerBackgroundSync(tag) {
    if ('serviceWorker' in navigator && 'sync' in ServiceWorkerRegistration.prototype) {
        try {
            const registration = await navigator.serviceWorker.ready;
            await registration.sync.register(tag);
            console.log(`Background sync registered: ${tag}`);
            return true;
        } catch (error) {
            console.error('Background sync registration failed:', error);
            return false;
        }
    }
    return false;
}

// Initialize PWA features on load
document.addEventListener('DOMContentLoaded', () => {
    updateOnlineStatus();
    requestPersistentStorage();
    checkStorageQuota();
    
    console.log('🚀 PWA features initialized for Simple Media Browser');
    console.log('📱 Running as PWA:', isPWA());
    console.log('📂 App folder: openverse');
    console.log('📦 Total files: 4');
});

// ============================================================================
// Original Application Code
// ============================================================================

const searchInput = document.getElementById('search-input');
const searchImagesButton = document.getElementById('search-images');
const searchAudioButton = document.getElementById('search-audio');
const resultsContainer = document.getElementById('results-container');
const modal = document.getElementById('modal');
const modalBody = document.getElementById('modal-body');
const closeButton = document.querySelector('.close-button');
const loadMoreButton = document.getElementById('load-more');
const licenseType = document.getElementById('license-type');
const source = document.getElementById('source');
const imageCategory = document.getElementById('image-category');
const audioCategory = document.getElementById('audio-category');
const imageCategoryFilter = document.getElementById('image-category-filter');
const audioCategoryFilter = document.getElementById('audio-category-filter');

const API_URL = 'https://api.openverse.org/v1';
let currentPage = 1;
let currentMediaType = '';
let currentQuery = '';

async function searchMedia(mediaType, newSearch = true) {
    if (newSearch) {
        currentPage = 1;
        resultsContainer.innerHTML = '';
        currentQuery = searchInput.value;
    }

    if (!currentQuery) {
        alert('Please enter a search query.');
        return;
    }

    currentMediaType = mediaType;

    let url = `${API_URL}/${mediaType}/?q=${currentQuery}&page=${currentPage}&mature=false`;

    if (licenseType.value) {
        url += `&license_type=${licenseType.value}`;
    }
    if (source.value) {
        url += `&source=${source.value}`;
    }
    if (mediaType === 'images' && imageCategory.value) {
        url += `&category=${imageCategory.value}`;
    } else if (mediaType === 'audio' && audioCategory.value) {
        url += `&category=${audioCategory.value}`;
    }

    try {
        const response = await fetch(`${url}&_=${new Date().getTime()}`);

        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }

        const data = await response.json();

        if (data.results.length === 0 && newSearch) {
            resultsContainer.innerHTML = '<p>No results found.</p>';
            loadMoreButton.style.display = 'none';
            return;
        }

        data.results.forEach(result => {
            const resultItem = document.createElement('div');
            resultItem.classList.add('result-item');

            if (mediaType === 'images') {
                const img = document.createElement('img');
                img.src = result.thumbnail;
                resultItem.appendChild(img);
            } else {
                const img = document.createElement('img');
                img.src = result.thumbnail;
                resultItem.appendChild(img);
            }

            const title = document.createElement('div');
            title.classList.add('title');
            title.textContent = result.title;
            resultItem.appendChild(title);

            resultItem.addEventListener('click', () => openModal(mediaType, result.id));

            resultsContainer.appendChild(resultItem);
        });

        if (data.page_count > currentPage) {
            loadMoreButton.style.display = 'block';
        } else {
            loadMoreButton.style.display = 'none';
        }

    } catch (error) {
        console.error('Error fetching data:', error);
        resultsContainer.innerHTML = `<p>Something went wrong. Please try again later. Error: ${error.message}</p>`;
    }
}

async function openModal(mediaType, id) {
    try {
        const response = await fetch(`${API_URL}/${mediaType}/${id}/?_=${new Date().getTime()}`);
        
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }

        const data = await response.json();

        let mediaElement = '';
        if (mediaType === 'images') {
            mediaElement = `<img src="${data.url}" style="max-width: 100%">`;
        } else if (mediaType === 'audio') {
            mediaElement = `<audio controls src="${data.url}"></audio>`;
        }

        modalBody.innerHTML = `
            <h2>${data.title}</h2>
            ${mediaElement}
            <p><strong>Creator:</strong> ${data.creator || 'Unknown'}</p>
            <p><strong>License:</strong> <a href="${data.license_url}" target="_blank">${data.license}</a></p>
            <p><a href="${data.foreign_landing_url}" target="_blank">View Original</a></p>
        `;

        modal.style.display = 'block';
    } catch (error) {
        console.error('Error fetching details:', error);
        modalBody.innerHTML = `<p>Could not load details. Error: ${error.message}</p>`;
    }
}

function loadMore() {
    currentPage++;
    searchMedia(currentMediaType, false);
}

searchImagesButton.addEventListener('click', () => {
    imageCategoryFilter.style.display = 'block';
    audioCategoryFilter.style.display = 'none';
    searchMedia('images');
});

searchAudioButton.addEventListener('click', () => {
    audioCategoryFilter.style.display = 'block';
    imageCategoryFilter.style.display = 'none';
    searchMedia('audio');
});

loadMoreButton.addEventListener('click', loadMore);

closeButton.addEventListener('click', () => {
    modal.style.display = 'none';
});

window.addEventListener('click', (event) => {
    if (event.target === modal) {
        modal.style.display = 'none';
    }
});

// The RSS feed we want to display
const rssFeedUrl = "https://api.adviceslip.com/daily_adviceslip.rss";

// We use the rss2json service to convert the RSS feed to JSON
const rssToJsonApiUrl = `https://api.rss2json.com/v1/api.json?rss_url=${encodeURIComponent(rssFeedUrl)}`;

// Get the container where we will display the advice
const adviceContainer = document.getElementById('advice-container');

// Fetch the data from the API
fetch(rssToJsonApiUrl)
    .then(response => response.json())
    .then(data => {
        // Check if the request was successful and if there are items
        if (data.status === 'ok' && data.items.length > 0) {
            // The advice is in the 'title' of the first item
            const dailyAdvice = data.items[0].title;
            
            // Clear the "Loading..." text
            adviceContainer.innerHTML = '';

            // Create a blockquote element for the advice
            const adviceElement = document.createElement('blockquote');
            adviceElement.textContent = `"${dailyAdvice}"`;
            
            // Add the advice to the container
            adviceContainer.appendChild(adviceElement);
        } else {
            adviceContainer.textContent = "Could not fetch advice at the moment.";
        }
    })
    .catch(error => {
        console.error("Error fetching advice:", error);
        adviceContainer.textContent = "Could not fetch advice at the moment.";
    });