/**
 * Service Worker for Utility Toolkit
 * Generated by PWA Converter v2.0.1
 * Cache Strategy: stale-while-revalidate
 * Folder: imgutls
 * Total Files Cached: 10
 */

const CACHE_NAME = 'imgutls-v1';
const OFFLINE_URL = '/imgutls/offline.html';

const urlsToCache = [
  "/imgutls/",
  "/imgutls/index.html",
  "/imgutls/manifest.json",
  "/imgutls/README.md",
  "/imgutls/index.html",
  "/imgutls/script.js",
  "/imgutls/style.css",
  "/imgutls/gifgen.html",
  "/imgutls/imgresize.html",
  "/imgutls/offline.html"
];

// Install event - cache ALL resources
self.addEventListener('install', event => {
    console.log('[Service Worker] Installing for Utility Toolkit...');
    console.log('[Service Worker] Caching 10 files...');
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then(cache => {
                console.log('[Service Worker] Caching app shell and all files');
                return cache.addAll(urlsToCache);
            })
            .then(() => {
                console.log('[Service Worker] All files cached successfully');
                return self.skipWaiting();
            })
            .catch(error => {
                console.error('[Service Worker] Cache failed:', error);
            })
    );
});

// Activate event - clean up old caches
self.addEventListener('activate', event => {
    console.log('[Service Worker] Activating...');
    event.waitUntil(
        caches.keys().then(cacheNames => {
            return Promise.all(
                cacheNames
                    .filter(name => name !== CACHE_NAME)
                    .map(name => {
                        console.log('[Service Worker] Deleting old cache:', name);
                        return caches.delete(name);
                    })
            );
        }).then(() => self.clients.claim())
    );
});

// Fetch event - serve from cache or network
self.addEventListener('fetch', event => {
        // Stale While Revalidate Strategy - Balanced approach
    if (event.request.method !== 'GET') {
        return;
    }

    event.respondWith(
        caches.match(event.request).then(cachedResponse => {
            const fetchPromise = fetch(event.request).then(response => {
                if (response.status === 200) {
                    const responseToCache = response.clone();
                    caches.open(CACHE_NAME).then(cache => {
                        cache.put(event.request, responseToCache);
                    });
                }
                return response;
            }).catch(error => {
                
                if (isNavigationRequest(event.request)) {
                    return caches.match(OFFLINE_URL);
                }
                throw error;
            });

            return cachedResponse || fetchPromise;
        })
    );
});


// Push notification handler
self.addEventListener('push', event => {
    console.log('[Service Worker] Push received');
    
    const options = {
        body: event.data ? event.data.text() : 'New notification from Utility Toolkit',
        icon: '/imgutls/icons/icon-192x192.png',
        badge: '/imgutls/icons/icon-72x72.png',
        vibrate: [200, 100, 200],
        tag: 'notification-tag',
        requireInteraction: false,
        actions: [
            { action: 'open', title: 'Open App' },
            { action: 'close', title: 'Close' }
        ]
    };

    event.waitUntil(
        self.registration.showNotification('Utility Toolkit', options)
    );
});

// Notification click handler
self.addEventListener('notificationclick', event => {
    console.log('[Service Worker] Notification clicked');
    event.notification.close();

    if (event.action === 'open' || !event.action) {
        event.waitUntil(
            clients.openWindow('/imgutls/')
        );
    }
});

// Background sync (if supported)
self.addEventListener('sync', event => {
    if (event.tag === 'sync-data') {
        event.waitUntil(syncData());
    }
});

async function syncData() {
    console.log('[Service Worker] Background sync triggered');
    // Implement your sync logic here
}

// Helper function to check if request is navigational
function isNavigationRequest(request) {
    return request.mode === 'navigate' || 
           (request.method === 'GET' && request.headers.get('accept').includes('text/html'));
}

console.log('[Service Worker] Loaded successfully for Utility Toolkit');
console.log('[Service Worker] Scope: /imgutls/');
console.log('[Service Worker] Caching 10 files including all your assets');