/**
 * Service Worker for Quran Search
 * Generated by PWA Converter v2.0.2
 */
const CACHE_NAME = 'quransearch-gh1';
const OFFLINE_URL = '/quransearch/offline.html';
const urlsToCache = [
  "/my-pwa-apps/quransearch/",
  "/my-pwa-apps/quransearch/index.html",
  "/my-pwa-apps/quransearch/manifest.json",
  "/my-pwa-apps/quransearch/quran.json",
  "/my-pwa-apps/quransearch/surahs.json",
  "/my-pwa-apps/quransearch/favicon-32x32.png",
  "/my-pwa-apps/quransearch/offline.html"
];
self.addEventListener('install', e => { e.waitUntil(caches.open(CACHE_NAME).then(c => c.addAll(urlsToCache)).then(() => self.skipWaiting())) });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(cN => Promise.all(cN.filter(n => n !== CACHE_NAME).map(n => caches.delete(n)))).then(() => self.clients.claim())) });
self.addEventListener('fetch', e => { if(e.request.method!=='GET')return;e.respondWith(caches.match(e.request).then(r=>{const f=fetch(e.request).then(res=>{if(res.status===200){const c=res.clone();caches.open(CACHE_NAME).then(ch=>ch.put(e.request,c))}return res}).catch(err=>{if(isNavigationRequest(e.request))return caches.match(OFFLINE_URL);throw err});return r||f})) });

function isNavigationRequest(r) { return r.mode === 'navigate' || (r.method === 'GET' && r.headers.get('accept').includes('text/html')); }
