/**
 * Service Worker for PWA Converter - Transform Web Apps into Progressive Web Apps
 * Cache Strategy: stale-while-revalidate
 * Generated by PWA Converter v2.1.0
 */

'use strict';

const CACHE_NAME = 'web2pwa-v3';
const OFFLINE_URL = '/my-pwa-apps/web2pwa/offline.html';
const urlsToCache = [
  "/my-pwa-apps/web2pwa/favicon.ico",
  "/my-pwa-apps/web2pwa/",
  "/my-pwa-apps/web2pwa/index.html",
  "/my-pwa-apps/web2pwa/manifest.json",
  "/my-pwa-apps/web2pwa/offline.html",
  "/my-pwa-apps/web2pwa/icons/icon-72x72.png",
  "/my-pwa-apps/web2pwa/icons/icon-192x192.png",
  "/my-pwa-apps/web2pwa/icons/icon-384x384.png",
  "/my-pwa-apps/web2pwa/icons/icon-512x512.png",
  "/my-pwa-apps/web2pwa/script.js",
  "/my-pwa-apps/web2pwa/styles.css",
  "/my-pwa-apps/web2pwa/script.js8icons"
];

self.addEventListener('install', event => {
    console.log('[Service Worker] Installing for PWA Converter - Transform Web Apps into Progressive Web Apps...');
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then(cache => {
                console.log('[Service Worker] Caching app shell and all files for PWA Converter - Transform Web Apps into Progressive Web Apps');
                return cache.addAll(urlsToCache);
            })
            .then(() => {
                console.log('[Service Worker] All files cached successfully for PWA Converter - Transform Web Apps into Progressive Web Apps');
                return self.skipWaiting();
            })
            .then(() => {
                // Request persistent storage to prevent cache eviction
                if (navigator.storage && navigator.storage.persist) {
                    navigator.storage.persist().then(granted => {
                        console.log('[Service Worker] Persistent storage granted:', granted);
                    });
                }
            })
            .catch(error => {
                console.error('[Service Worker] Caching failed for PWA Converter - Transform Web Apps into Progressive Web Apps:', error);
            })
    );
});

self.addEventListener('activate', event => {
    console.log('[Service Worker] Activating for PWA Converter - Transform Web Apps into Progressive Web Apps...');
    event.waitUntil(
        caches.keys().then(cacheNames => {
            return Promise.all(
                cacheNames
                    .filter(name => {
                        const cachePrefix = CACHE_NAME.replace(/-v\d+$/, "");
                        return name.startsWith(cachePrefix + "-") && name !== CACHE_NAME;
                    })
                    .map(name => {
                        console.log('[Service Worker] Deleting old cache:', name);
                        return caches.delete(name);
                    })
            );
        }).then(() => self.clients.claim())
    );
});

// Fetch event - Optimized Cache-First Strategy
self.addEventListener('fetch', event => {
    if (event.request.method !== 'GET') return;

    // Handle Favicon
    if (event.request.url.includes('favicon.ico')) {
        event.respondWith(
            caches.match(event.request).then(response => {
                return response || fetch(event.request).catch(() => new Response(null, { status: 204 }));
            })
        );
        return;
    }

    // Main Strategy: Cache-First
    event.respondWith(
        caches.match(event.request).then(cachedResponse => {
            // If found in cache, return immediately
            if (cachedResponse) return cachedResponse;

            // Otherwise, get from network and add to cache
            return fetch(event.request).then(response => {
                if (response && response.status === 200) {
                    const responseToCache = response.clone();
                    caches.open(CACHE_NAME).then(cache => {
                        cache.put(event.request, responseToCache);
                    });
                }
                return response;
            }).catch(() => {
                // If offline and navigating, show offline page
                if (isNavigationRequest(event.request)) {
                    return caches.match(OFFLINE_URL);
                }
            });
        })
    );
});

function isNavigationRequest(request) {
    return request.mode === 'navigate' ||
           (request.method === 'GET' && request.headers.get('accept').includes('text/html'));
}

console.log('[Service Worker] Loaded successfully for PWA Converter - Transform Web Apps into Progressive Web Apps');
console.log('[Service Worker] Scope: /my-pwa-apps/web2pwa/');
